from google.adk.agents import Agent
from google import genai
from google.genai import types
import os
import uuid
import json
import asyncio
from geminaise_agent.semantic_search import find_best_product, precompute_product_embeddings

# Store the latest user images per session
latest_user_images = {}
latest_tryon_urls = {}       # Images generated by gemini-3.1-flash-image-preview
latest_tryon_videos = {}     # Videos generated by veo-3.1-generate-001 (populated by video_manager.py)

# ----------- existing find_product_image and try_on_apparel -----------

def find_product_image(product_name: str) -> bytes:
    """Attempt to find the pre-generated product image based on the product name."""
    try:
        products_path = os.path.join(os.path.dirname(__file__), "..", "..", "data", "products.json")
        if not os.path.exists(products_path):
            return None
            
        with open(products_path, "r") as f:
            products = json.load(f)
            
        # Very simple fuzzy match - check if any word in the product name matches
        best_match = None
        for p in products:
            if product_name.lower() in p["name"].lower() or p["name"].lower() in product_name.lower():
                best_match = p
                break
                
        if not best_match:
            # Fallback: just check for brand or category
            for p in products:
                if p["brand"].lower() in product_name.lower() or p["category"].lower() in product_name.lower():
                    best_match = p
                    break
                    
        if best_match:
            image_path = os.path.join(os.path.dirname(__file__), "..", "..", "data", "images", f"{best_match['id']}.png")
            if os.path.exists(image_path):
                with open(image_path, "rb") as f:
                    return f.read()
    except Exception as e:
        print(f"Error finding product image: {e}")
        
    return None

async def try_on_apparel(product_query: str, setting: str = "studio lighting") -> str:
    """
    Use this tool when the user asks to try on a specific apparel item, piece of clothing, or outfit.
    Describe the item in natural language — the system will automatically find the best matching product.
    
    Args:
        product_query: A natural language description of what the user wants to try on
                       (e.g. "something sporty", "a pencil skirt", "a cozy sweater", "a tweed jacket").
                       Be as descriptive as possible about style, colour, or type.
        setting: The background setting (e.g. "at the beach", "in a cafe", "studio lighting"). Defaults to studio lighting.
    """
    # Find the latest user image
    if not latest_user_images:
        return "I'm sorry, but I don't have a photo of you yet. Please upload a photo first."
    
    # Semantically match the query to the product catalogue
    matched_product = find_best_product(product_query)
    product_name = matched_product["name"]
    product_category = matched_product.get("category", "")
    print(f"[Agent] Semantic match: '{product_query}' → '{product_name}' (score={matched_product.get('score', 0):.3f})")

    # Get the last uploaded image
    session_id, user_image_bytes = list(latest_user_images.items())[-1]
    
    try:
        prompt = f"Seamlessly dress the person in the provided photo with the '{product_name}' ({product_category}), placing them in a realistic {setting}. CRITICALLY IMPORTANT: You must perfectly preserve the original person's face, facial features, identity, hair, and body type exactly as they appear in the original image. Do not change their face at all."
        
        contents = [
            types.Part.from_bytes(data=user_image_bytes, mime_type="image/jpeg")
        ]
        
        product_image_bytes = find_product_image(product_name)
        if product_image_bytes:
            contents.append(types.Part.from_bytes(data=product_image_bytes, mime_type="image/png"))
            prompt += " Use the second image as the reference for the clothing item."
            
        contents.append(prompt)

        # Run the slow image generation in a background thread to avoid blocking
        # the asyncio event loop (which causes 1006 keepalive ping timeout crashes).
        def _generate():
            sync_client = genai.Client()
            return sync_client.models.generate_content(
                model='gemini-3.1-flash-image-preview',
                contents=contents,
                config=types.GenerateContentConfig(
                    response_modalities=["IMAGE"],
                ),
            )

        print("[Agent] Starting image generation in background thread…")
        result = await asyncio.get_event_loop().run_in_executor(None, _generate)
        print("[Agent] Image generation complete.")
        
        if result.candidates and result.candidates[0].content.parts:
            part = result.candidates[0].content.parts[0]
            if part.inline_data:
                filename = f"{uuid.uuid4()}.jpg"
                filepath = os.path.join(os.path.dirname(__file__), "..", "static", "tryon_images", filename)
                
                os.makedirs(os.path.dirname(filepath), exist_ok=True)
                with open(filepath, "wb") as f:
                    f.write(part.inline_data.data)
                    
                image_url = f"/static/tryon_images/{filename}"
                latest_tryon_urls[session_id] = image_url
                
                # Return a simple string with context
                return f"I have successfully generated the image of you wearing the {product_name} {setting}. The image is now displayed on the user's screen. Tell the user their image is ready!"
                
        return "I tried to generate the image, but something went wrong with the image generation service."
        
    except Exception as e:
        print(f"Error generating try-on image: {e}")
        return f"I encountered an error while trying to generate the image: {str(e)}"

# ----------- new suggest_products (existing) and generate_video -----------

def suggest_products(user_query: str) -> str:
    """
    Search the product catalogue for items matching the user's description.
    ALWAYS call this tool first when a user asks about trying on clothes or asks what you have.
    Returns the top 3 matching products so you can tell the user what's available.

    Args:
        user_query: What the user is looking for, e.g. "a nice jacket", "something casual".
    """
    from geminaise_agent.semantic_search import _product_embeddings, _embed_text
    import numpy as np

    if not _product_embeddings:
        from geminaise_agent.semantic_search import precompute_product_embeddings
        precompute_product_embeddings()

    query_vec = _embed_text(user_query)
    scored = []
    for entry in _product_embeddings:
        score = float(np.dot(query_vec, entry["embedding"]))
        scored.append((score, entry["product"]))
    scored.sort(reverse=True)

    top3 = scored[:3]
    lines = []
    for i, (score, p) in enumerate(top3, 1):
        lines.append(f"{i}. {p['name']} ({p['category']}, £{p['retail_price']:.2f})")

    result = "Here are the closest matching products in our catalogue:\n" + "\n".join(lines)
    print(f"[Agent] suggest_products('{user_query}') →\n{result}")
    return result


async def generate_video(prompt: str) -> str:
    """
    Call this tool when the user asks to see a video of the outfit they just tried on.
    
    Args:
        prompt: A prompt describing HOW the person should move to show off the clothing functionally.
                (e.g., 'The person walks confidently forward, the fabric of the jacket draping naturally',
                'The person turns slowly to show how the skirt flows in motion').
    """
    if not latest_tryon_urls:
        return "I cannot generate a video because no try-on image has been created yet. Please use the try_on_apparel tool first."

    # Get the latest generated image (not the webcam one).
    session_id, latest_image_url = list(latest_tryon_urls.items())[-1]
    
    # Resolve URL back to local file path
    filename = latest_image_url.split("/")[-1]
    filepath = os.path.join(os.path.dirname(__file__), "..", "static", "tryon_images", filename)
    
    if not os.path.exists(filepath):
        return "Sorry, I lost track of the try-on image."

    with open(filepath, "rb") as f:
        img_bytes = f.read()

    try:
        from geminaise_agent.video_manager import _get_vertex_client, start_video_polling
        
        # Start Veo generation in a background thread
        def _start_veo():
            client = _get_vertex_client()
            return client.models.generate_videos(
                model='veo-3.1-generate-001',
                prompt=prompt,
                image=types.Image(image_bytes=img_bytes, mime_type='image/jpeg'),
                config=types.GenerateVideosConfig(
                    aspect_ratio='9:16', # Standard phone portrait
                    duration_seconds=5,
                    number_of_videos=1,
                    fps=24,
                ),
            )
        
        print(f"[Agent] Starting Veo 3.1 video generation with prompt: '{prompt}'")
        operation = await asyncio.get_event_loop().run_in_executor(None, _start_veo)
        
        # Start polling immediately, non-blocking
        start_video_polling(operation.name, session_id)
        
        return "I have started generating the video. It will take a few minutes to render. Tell the user it's rendering and they will see it when it's done, and feel free to keep chatting."
        
    except Exception as e:
        print(f"Error starting video generation: {e}")
        return f"I encountered an error trying to start the video: {e}"


root_agent = Agent(
    name="geminAIse",
    model="gemini-2.5-flash-native-audio-preview-12-2025",
    description="A Live API Virtual Try-On Assistant that acts as a personal shopper and stylist.",
    instruction=(
        "You are geminAIse, a helpful, enthusiastic, and friendly personal shopper and virtual stylist. "
        "You help users pick out outfits, provide fashion advice, and most importantly, allow them to virtually try on clothes. "
        "You have access to a live video stream from the user's camera (or their uploaded photos). "
        "\n\n"
        "CRITICAL PRODUCT RULES — follow these strictly:\n"
        "1. You ONLY stock the products returned by the suggest_products tool. You must NEVER mention, recommend, or invent any product that is not in our catalogue.\n"
        "2. When a user asks what you have, or what they could try on, ALWAYS call suggest_products first and then tell the user ONLY those results.\n"
        "3. When a user wants to try something on, call suggest_products to find the best match, confirm the matched product name with the user, then call try_on_apparel.\n"
        "4. When calling try_on_apparel, pass the exact product description from suggest_products as the product_query.\n"
        "5. When a user asks for a VIDEO of an outfit, call the generate_video tool. The prompt should realistically show off the fabric and fit (e.g. 'strutting down a runway', 'turning slowly'). The video takes 5 minutes to render, so politely let the user know they can keep chatting while they wait.\n"
        "\n"
        "Keep your responses concise and conversational. "
        "CRITICAL INSTRUCTION: You communicate via voice. You MUST NOT output any internal thoughts, monologues, or actions. "
        "NEVER use asterisks (*) or markdown formatting. Speak directly and naturally to the user."
    ),
    tools=[suggest_products, try_on_apparel, generate_video]
)

# Pre-compute product embeddings at import time (uses cache if available, fast)
try:
    precompute_product_embeddings()
except Exception as e:
    print(f"[SemanticSearch] Warning: could not precompute embeddings at startup: {e}")
